<?php
$this->headTitle($this->translate('Trang sửa mật khẩu tài khoản'));
// $this->headLink(['rel' => 'canonical', 'href' => $this->template()->loadValue('CANONICAL_USER_CHANGEPASSWORD')]);
$this->headScript()->appendFile('/js/jquery/jquery.validationEngine-vi.js');
$this->headScript()->appendFile('/js/jquery/jquery.validationEngine.js');
$this->headScript()->appendFile('/tp/T0367/js/user.js');
$this->headLink()->appendStylesheet('/css/validationEngine.jquery.css');
$this->headLink()->appendStylesheet($this->libs()->srcLink([
    '/tp/T0367/css/user.css',
], 1));
$this->inlineScript()->append($this->headScript()->createData('text/javascript', array(), "$(function(){ Address.load(); });"));
/*@var $user \User\Model\User */
$user = $this->user()->getUser();
?>
<div class="container">
    <div class="row">
        <div id="breadcrumb" class="w100 col-lg-12 col-xs-12 col-sm-12 col-md-12">
            <ul class="breadcrumb" style="margin-bottom: 10px">
                <li><a href="/"><?= $this->translate('Trang chủ') ?></a></li>
                <li><a href="/profile"><?= $this->translate('Thông tin tài khoản') ?></a></li>
                <li><a><?= $this->translate('Đổi mật khẩu') ?></a></li>
            </ul>
        </div>
        <div class="col-xs-12 col-lg-3 col-md-8 col-sm-3">
            <div class="sidebar">
                <div id="headerProfile">
                    <p id="avatarProfile">
                        <img src="/img/avatar_comment.png" alt="avatar"/>
                    </p>
                    <h3><?= $this->escapeHtml($user->getFullName()) ?></h3>
                    <p><?= $user->getEmail() ?></p>
                    <span class="clearfix"></span>
                </div>
                <span class="prfTile"><?= $this->translate('Đơn hàng') ?></span>
                <ul id="profileMenu">

                    <li><a href="/order"><i class="fas fa-envelope"></i> <?= $this->translate('Quản trị đơn hàng') ?>
                        </a></li>
                </ul>
                <span class="prfTile"><?= $this->translate('Hồ sơ') ?></span>
                <ul id="profileMenu">
                    <li><a rel="nofollow" href="/profile"><i
                                    class="fas fa-user"></i> <?= $this->translate('Trang cá nhân') ?></a></li>
                    <li><a rel="nofollow" href="/user/signout"><i
                                    class="fas fa-sign-out"></i> <?= $this->translate('Thoát') ?></a></li>
                </ul>
            </div>

        </div>
        <div class="col-xs-12 col-lg-9 col-md-9 col-sm-9 profileRight">
            <div class="ctrl-wrapper">
                <div id="profileContent">
                    <div class="block"><h1 class="section-title">
                            Đổi mật khẩu tài khoản cá nhân</h1></div>
                    <div id="profileIf">
                        <form id="formAcount" class="formAcount validate" method="post">
                            <?php if ($this->message) { ?>
                                <div id="showMesage" class="form-group clearfix">
                                    <div class="alert alert-warning"><?= $message ?></div>
                                    <script type="text/javascript">
                                        setTimeout(function () {
                                            $('#showMesage').fadeOut(100);
                                            $('#showMesage').remove();
                                        }, 5000)
                                    </script>
                                </div>
                            <?php } ?>
                            <div class="form-group clearfix">
                                <input type="password" id="oldpassword" name="oldpassword"
                                       placeholder="<?= $this->translate('Mật khẩu cũ') ?>"
                                       class="validate[required],minSize[6] form-control inputAccount">
                                <input type="password" id="newpassword" name="newpassword"
                                       placeholder="<?= $this->translate('Mật khẩu mới') ?>"
                                       class="validate[required],minSize[6] form-control inputAccount">
                                <input type="password" id="repassword" name="repassword"
                                       placeholder="<?= $this->translate('Xác Mật khẩu') ?>"
                                       class="validate[required],minSize[6] form-control inputAccount">
                                <button type="submit"
                                        class="btn btn-green btnAcess"> <?= $this->translate('Xác nhận') ?></button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<style>
    .profile li label {
        display: block;
    }

    .profile li input.tb {
        width: 100%;
    }

    #profileContent {
        padding: 0 5%;
    }

    #formAcount .inputAccount {
        width: 70%;
        height: 48px;
        border: 1px solid #eaebf3;
        border-radius: 3px;
        outline: none;
        color: #000;
        padding: 0 18px;
        font-weight: 500;
        -webkit-appearance: none;
        transition: border-color .2s ease-in-out, box-shadow .2s ease-in-out, color .2s ease-in-out;
        margin-bottom: 10px;
    }

    .userbox.phone input, .userbox input[type=email], .userbox input[type=password], .userbox input[type=text], .userbox input[type=tel] {
        width: 100%;
        height: 55px;
        border: 1px solid transparent;
        background: #ededed;
        color: #000;
        padding: 0 20px;
        font-weight: 500;
        -webkit-appearance: none;
    }

    input.form-control {
        box-shadow: none;
        border-radius: 3px;
        font-size: 14px;
        height: 42px;
        border: 1px solid #d5d4d4;
        box-shadow: 0 1px rgb(212 214 216 / 25%) inset;
        transition: border-color .2s ease-in-out, box-shadow .2s ease-in-out, color .2s ease-in-out;
    }

    .form-control {
        display: block;
        width: 100%;
        height: calc(1.5em + 0.75rem + 2px);
        padding: 0.375rem 0.75rem;
        font-size: 1rem;
        font-weight: 400;
        line-height: 1.5;
        color: #495057;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #ced4da;
        border-radius: 0.25rem;
        transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
    }

    .userbox.phone input, .userbox input[type=email], .userbox input[type=password], .userbox input[type=text], .userbox input[type=tel] {
        width: 100%;
        height: 55px;
        border: 1px solid transparent;
        background: #ededed;
        padding: 0 20px;
        font-weight: 500;
        -webkit-appearance: none;
    }

    .form-group .btnAcess {
        background: #000;
        color: #fff;
        border: 1px solid #000;
        display: block;
        border-radius: 3px;
        font-size: 12px;
        padding: 0 30px;
        height: 45px;
        line-height: 45px;
        text-transform: uppercase;
        font-weight: 600;
        width: 70%;
    }

</style>