<?php
$storeId = $GLOBALS['domainConfigs']['storeId'];
$title = '';
if (isset($this->q)) {
    $title = $this->escapeHtml($this->q);
}
$this->headTitle($this->translate('Kết quả tìm kiếm:') . ' ' . $this->escapeHtml($title));
$this->headMeta()->appendProperty('og:title', 'Kết quả tìm kiếm: ' . $this->escapeHtml($title));
/* @var $prodCategory \Product\View\Helper\ProductCategory */

/* @var $paginator \Zend\Paginator\Paginator */
$paginator = $this->paginator;
$paginator->setItemCountPerPage($this->uriParams()->getRequest()->getQuery('icpp') ?: 1);
$paginator->setPageRange(5);

$this->headLink([
    'rel' => 'canonical',
    'href' => getCurrentFullUrl(true) . "/search"
]);
$paramSearch = $this->uriParams()->getRequest()->getQuery('q');
$show = $this->uriParams()->getRequest()->getQuery('show');
$parseUrl = parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH);
$page = $this->uriParams()->getRequest()->getQuery('page');
$icpp = $this->uriParams()->getRequest()->getQuery('icpp');
echo '<link rel="canonical" rel="nofollow" href="/search" />';

$priced = ' ₫';
$totalProducts = $paginator->getTotalItemCount();

?>
<main class="search">
    <ul class="navigation">
        <li><a href="/">Trang chủ</a></li>
        <li><a href="/product?q=<?= $title ?>">Tìm kiếm - <?= $title ?></a></li>
    </ul>
    <h1 class="h3 text-uppercase text-center fw-normal mt-3 mb-5">Tìm kiếm - <?= $title ?></h1>
    <div class="text-search">
        <p>có <?= $totalProducts ?>  sản phẩm</p>
    </div>
    <div class="search-product">
        <div class="margin-search">
            <?php
            if ($paginator) {
            ?>
                <div class="new-product-women-search container-fluid">
                    <?php
                    /* @var $p \Product\Model\Store */
                    foreach ($paginator->getCurrentModels() as $p) {
                        $priceDiscount = $p->getPriceAfterDiscount();
                        $percent = $p->calcDiscountPercent();
                        $oldPrices = $p->getOldPrice();
                        ?>
                        <div class="product-new-list col-lg-3 col-md-4 col-sm-6 col-6 " data-id="<?= $p->getId() ?>">
                            <div class="product-women">
                                <div class="product-women-img">
                                    <a class="grid-view-item__link" href="<?= $p->getViewLink() ?>"
                                       title="<?= $p->getName() ?>">
                                        <picture>
                                            <source class="imglarge" data-srcset="<?= $p->getThumbnailUri(); ?>">
                                            <source class="imgsmall" data-srcset="<?= $p->getThumbnailUri(); ?>">
                                            <img alt="<?= $p->getName() ?>" class="lazyload img_thumb_product" width="400" height="600" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsQAAA7EAZUrDhsAAAANSURBVBhXYzh8+PB/AAffA0nNPuCLAAAAAElFTkSuQmCC">
                                        </picture>

                                    </a>
                                    <a class="wishlist-btn wishlist-product" href="javascript:void(0)" psId="<?= $p->getId() ?>">
                                        <i class="far fa-heart"></i>
                                    </a>
                                    <?php
                                    if ($percent) {
                                        ?>
                                        <div class="goodsli-discount">
                                            <div class="disc-txt">
                                                <div class="disc-nowrap">
                                                <span class="disc-num">
                                                    <span class="j-item-discount"><?= $percent ?></span>
                                                </span>%
                                                </div>
                                                off
                                            </div>
                                        </div>
                                        <?php
                                    }
                                    ?>
                                </div>
                                <div class="button-add tp_button">
                                    <button title="Xem nhanh" class="action quick-view"
                                            data-id="<?= $p->getId() ?>">
                                        <span>Xem nhanh</span>
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                             xmlns:xlink="http://www.w3.org/1999/xlink"
                                             version="1.1" id="Capa_1" x="0px" y="0px"
                                             viewBox="0 0 59.2 59.2"
                                             style="enable-background:new 0 0 59.2 59.2;"
                                             xml:space="preserve"><g>
                                                <path d="M51.062,21.561c-11.889-11.889-31.232-11.889-43.121,0L0,29.501l8.138,8.138c5.944,5.944,13.752,8.917,21.561,8.917   s15.616-2.972,21.561-8.917l7.941-7.941L51.062,21.561z M49.845,36.225c-11.109,11.108-29.184,11.108-40.293,0l-6.724-6.724   l6.527-6.527c11.109-11.108,29.184-11.108,40.293,0l6.724,6.724L49.845,36.225z"/>
                                                <path d="M28.572,21.57c-3.86,0-7,3.14-7,7c0,0.552,0.448,1,1,1s1-0.448,1-1c0-2.757,2.243-5,5-5c0.552,0,1-0.448,1-1   S29.125,21.57,28.572,21.57z"/>
                                                <path d="M29.572,16.57c-7.168,0-13,5.832-13,13s5.832,13,13,13s13-5.832,13-13S36.741,16.57,29.572,16.57z M29.572,40.57   c-6.065,0-11-4.935-11-11s4.935-11,11-11s11,4.935,11,11S35.638,40.57,29.572,40.57z"/>
                                            </g></svg>
                                    </button>
                                    <?php
                                    if ($p->getParentId() == $p::PS_PARENT_ROOT) {
                                        echo '<button title="Mua ngay" class="action add-to-cart" onclick="location.href=' . "'" . ($p->getViewLink()) . "'" . '">';
                                    } else {
                                        echo '<button title="Mua ngay" class="action add-to-cart flytocart" data-buy="1" data-psId="' . $p->getId() . '">';
                                    }
                                    ?>
                                    <span>Mua ngay</span>
                                    <svg xmlns="http://www.w3.org/2000/svg"
                                         xmlns:xlink="http://www.w3.org/1999/xlink"
                                         version="1.1" id="Capa_1" x="0px" y="0px"
                                         width="27.948px" height="27.948px"
                                         viewBox="0 0 27.948 27.948"
                                         style="enable-background:new 0 0 27.948 27.948;"
                                         xml:space="preserve"><g>
                                            <path d="M9.689,19.484h15.503v1.936H8.133L4.99,7.153h-4.3V5.218h5.854L9.689,19.484z M11.45,22.708   c-1.447,0-2.62,1.172-2.62,2.619c0,1.446,1.173,2.621,2.62,2.621c1.447,0,2.62-1.175,2.62-2.621   C14.07,23.88,12.897,22.708,11.45,22.708z M22.25,22.708c-1.445,0-2.619,1.172-2.619,2.619c0,1.446,1.174,2.621,2.619,2.621   c1.447,0,2.621-1.175,2.621-2.621C24.872,23.88,23.698,22.708,22.25,22.708z M10.668,18.035L8.37,6.133h3.76L20.463,0l3.729,5.064   l-0.161,1.069h3.227l-2.687,11.902H10.668z M23.584,5.477l-0.892,0.656h0.794L23.584,5.477z M13.038,6.132h1.958l-0.117-0.16   l0.379-0.279l0.324,0.439h0.48L15.57,5.463l0.38-0.279l0.697,0.948h0.544l-0.89-1.207l0.381-0.279l1.095,1.486h0.626l-1.301-1.768   l0.379-0.28l1.507,2.048h0.544l-1.697-2.308l0.379-0.278l1.902,2.586h1.668l1.639-1.205l-3.07-4.176L13.038,6.132z M21.75,5.305   l-2.088-2.839l-0.382,0.279l2.089,2.839L21.75,5.305z M21.02,5.845l-2.09-2.84l-0.379,0.279l2.092,2.839L21.02,5.845z"/>
                                        </g></svg>
                                    </button>
                                </div>
                            </div>
                            <div class="product-caption ">
                                <a class="item-url" href="<?= $p->getViewLink() ?>">
                                    <div class="marker new-product">
                                        <h3 class="item-title">
                                            <a href="<?= $p->getViewLink() ?>"
                                               title="<?= $p->getName() ?>"> <?= $p->getName() ?>
                                            </a>
                                        </h3>
                                    </div>
                                    <div class="item-price">
                                        <?php
                                        if ($priceDiscount > 0) {
                                            echo '<span class="pro-price-del"><del class="compare-price tp_product_price_old">' . number_format($p->getPrice()) . $priced . '</del></span>';
                                            echo '<span class="tp_product_price price-sale">' . number_format($priceDiscount) . $priced . '</span>';
                                        } else if (empty($p->getPrice()) || $p->getPrice() <= 0 || $p->getContactPrice()) {
                                            $link = 'javascript:';
                                            $taget = '';
                                            echo '<a href="' . $link . '" ' . $taget . '><span class="tp_product_price">' . $this->template()->loadValue('PRICE_CONTACT') . '</span></a>';
                                        } else {
                                            $sale = '';
                                            if ($p->getOldPrice()) {
                                                $sale = 'price-sale';
                                                echo '<span class="pro-price-del"><del class="compare-price tp_product_price_old">' . number_format($p->getOldPrice()) . $priced . '</del></span>';
                                            }
                                            echo '<span class="tp_product_price ' . $sale . '">' . number_format($p->getPrice()) . $priced . '</span>';
                                        }
                                        ?>
                                    </div>
                                </a>
                            </div>
                        </div>
                    <?php } ?>
                </div>
                <?php
            }
            ?>
        </div>
        <div class="sortpagibar pagi clearfix text-center">
            <?php
            if ($paginator) {
                echo $this->paginationControl($paginator, 'Sliding', 'partial/paginatorBoostrap');
            }
            ?>
        </div>
    </div>
</main>