<?php
$storeId = $GLOBALS['domainConfigs']['storeId'];
$this->headTitle($this->translate('Reset password tài khoản'));
$this->headScript()->appendFile('/js/jquery/jquery.validationEngine-vi.js');
$this->headScript()->appendFile('/js/jquery/jquery.validationEngine.js');
$this->headScript()->appendFile('/tp/T0367/js/user.js');
$this->headLink()->appendStylesheet($this->libs()->srcLink([
    '/tp/T0367/css/user.css',
], 1));
$this->inlineScript()->append($this->headScript()->createData('text/javascript', array(), "$(function(){ Address.load(); });"));
$container="container-fluid";
$bnBreadcrumb = $this->store()->getBannerByPositionCode('BACKGROUND_BREADCRUMB',['limit'=>1]);
?>
<main class="">

    <div class="layout-account forgot-password">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 col-xs-12 wrapbox-heading-page">
                    <div class="header-page clearfix">
                        <h1 class="header-user-forgot-password"><?= $this->translate('Quên mật khẩu') ?></h1>
                    </div>
                </div>
                <div class="col-md-6 col-xs-12 wrapbox-content-page ">
                    <div id="customer-login">
                        <div id="login" class="userbox">
                            <div class="accounttype">
                                <h2 class="title"></h2>
                            </div>
                            <div id="customer_login">
                                <?php
                                if ($this->success) {
                                    echo '<div class="desc-modal alert alert-success">Vui lòng kiểm tra email và ấn vào đường dẫn tạo mật khẩu mới!</div>';
                                }
                                else {
                                    if ($this->message) {
                                        echo '<div class="desc-modal alert alert-danger">'.$this->message.'</div>';
                                    }
                                    $partial = $this->partial('partial/form', ['form' => $this->form]);
                                    $partial = str_replace('class="f"','class="f validate"',$partial);
                                    echo $partial;
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
<style>
    #customer_login ul li {
        margin-bottom: 30px;
    }
    #customer_login ul li.btns{
        margin-bottom: 0;
    }
    #customer_login ul li.btns input{
        width: 100%;
    }
    .errors li{
        padding: 10px 0 0 0;
        font-style: italic;
        color: red;
    }
</style>

